services:
  - type: web
    name: vote-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    python_version: 3.11.8
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
